blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from home.views import home_view
from web_dersleri.views import hello_django,play
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',home_view),

    url(r'^post/',include('post.urls')),

    url(r'^Hello',hello_django),
    url(r'^Play/(S[0-9]+)/',play),
]

post/urls.py
from django.conf.urls import url
from .views import *

app_name = "post"

urlpatterns = [
    url(r'^index/$',post_index,name="index"),
    url(r'^(?P<id>\d+)/$',post_detail,name="detail"),
    url(r'^create/$',post_create,name="create"),
    url(r'^update/$', post_update,name="update"),
    url(r'^delete/$', post_delete,name="delete"),

]

home/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=120,verbose_name="Başlık")
    content = models.TextField(verbose_name="İçerik")
    publishing_date = models.DateTimeField(verbose_name="Yayınlanma Tarihi")

    def __str__(self):
        return  self.title

web_dersleri/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.

def home_view(request):
    if request.user.is_authenticated:
        context = {
            'isim' : 'Kullanıcı'
        }
    else:
        context = {
            'isim':'Misafir'
        }
    return render(request,'home.html',context)

post/views.py
from django.shortcuts import render,HttpResponse,get_object_or_404
from .models import Post
# Create your views here.

def post_index(request):
    posts = Post.objects.all()
    return render(request,"post/index.html",{"posts": posts })

def post_detail(request,id):
    post = get_object_or_404(Post,id=id)
    context = {
        "post":post,
    }
    return  render(request,"post/detail.html",context)

def post_create(request):
    return HttpResponse("<h1>Post Create Sayfası</h1>")

def post_update(request):
    return HttpResponse("<h1>Post Update Sayfası</h1>")

def post_delete(request):
    return HttpResponse("<h1>Post Delete Sayfası</h1>")

web_dersleri/views.py
from django.shortcuts import render,HttpResponse

# Create your views here.

def hello_django(request):
    return  HttpResponse("<h1>Hello World</h1>")

def play(request , sarki_kodu):
    sarkilar = {
        u"S01" : (u"Eminem",u"Monster"),
        u"S02" : (u"Adele", u"Bilmem ne şarkısı"),
        u"S03" : (u"Şarkıcı" , u"Şarkı")
    }

    if sarki_kodu in sarkilar.keys():
        html = u"Şarkıcı .. : {}\nŞarkı Adı .. : {}".format(
            sarkilar[sarki_kodu][0] , sarkilar[sarki_kodu][1]
        )
    else:
        html = u"Şarkı bulunamadı"

    return HttpResponse(html)

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <h1>Hoşgeldin .. : {{isim}}</h1>

</body>
</html>

templates/post/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


     {{ post.id }}<br>
     {{ post.title }}<br>
     {{ post.content }}<br>
     {{ post.publishing_date }}<br><hr>


</body>
</html>

templates/post/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<hr>


    {% for post in posts %}

        {{ post.id }}<br>
        <a href="{% url 'post:detail' id = post.id %}" >{{ post.title }}<br></a>
        {{ post.content }}<br>
        {{ post.publishing_date }}<br><hr>

    {% endfor %}

</body>
</html>